# Generated by Django 4.2.23 on 2025-07-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentconfig',
            name='environment',
            field=models.CharField(choices=[('dev', 'Development'), ('prod', 'Production')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='processinglimits',
            name='environment',
            field=models.CharField(choices=[('dev', 'Development'), ('prod', 'Production')], default='prod', max_length=20),
        ),
    ]
